### ISSUE TITLE
Support for HTTPS

### ISSUE THREAD

**Issue by mlamoure** [FlyingDiver/Indigo-HTTPd#1]
Enjoying the plugin.  I think supporting HTTPS would let me sleep better at night, given the sensitivity of the data being sent from IFTTT to the Indigo box.  I'm not certain if IFTTT will complain about self-signed certs.  I've done some searching and I couldn't find a definitive answer.  Assuming they will accept self signed certs, I think moving this to HTTPS would be a great feature add.

**Comment by FlyingDiver** [comment]
Release 1.1.0.
