### ISSUE TITLE
Access Denied Error

### ISSUE THREAD

**Issue by brandonjones24** [FlyingDiver/Indigo-HTTPd#2]
Hey Joe,

I am receiving an access denied error on initial setup. I believe my port forward and domain are OK, and my username and password seem to be fine.

Any idea what I may be missing?
"/setvar?livingroomsleep=true"

**Comment by brandonjones24** [comment]
To clarify, it's reaching indigo, Im just not sure what the cause of the access denial is.

**Comment by FlyingDiver** [comment]
http or https?  

Log excerpt?

**Comment by FlyingDiver** [comment]
Did you follow the instructions on https://github.com/FlyingDiver/Indigo-HTTPd/wiki/Using-HTTPS?

**Comment by brandonjones24** [comment]
I'm using http, however I went ahead and added the self signed cert to see if that helps. This is now in the indigo 7 folder on the server.

When restarting the plugin, I see the following in the log file:
2018-07-15 07:13:17.322	[   DEBUG]               Plugin.__init__                 logLevel = 10
2018-07-15 07:13:17.707	[   DEBUG]               Plugin.start_server             Started HTTP server on port 5555
2018-07-15 07:14:27.905	[   DEBUG]               Plugin.__init__                 logLevel = 10
2018-07-15 07:14:27.932	[   DEBUG]               Plugin.start_server             Started HTTP server on port 5555

**Comment by brandonjones24** [comment]
Here's the error I am seeing in the event log: https://www.screencast.com/t/GHcOFfcT

**Comment by FlyingDiver** [comment]
That's not an error from the plugin, that's from Indigo's web server (I think).  Which means your port forward is not set up correctly.

**Comment by brandonjones24** [comment]
Ah, thanks!
OK, rookie question, what should my internal port be set to? Currently it’s the default in my indigo server start page.

On Sun, Jul 15, 2018 at 7:23 AM, Joe Keenan <notifications@github.com> wrote:
That's not an error from the plugin, that's from Indigo's web server (I think). Which means your port forward is not set up correctly.

**Comment by FlyingDiver** [comment]
> On Jul 15, 2018, at 7:32 AM, brandonjones24 <notifications@github.com> wrote:
> 
> Ah, thanks!
> OK, rookie question, what should my internal port be set to? Currently it’s the default in my indigo server start page.

Same as the external, which is the same as configured in the plugin.  Or more accurately, the internal port is what’s configured in the plugin.  The external can be different, it’s what you use in the IFTTT URL.

**Comment by brandonjones24** [comment]
Thanks for your patience. That mistake on my part caused the HTTP issues. HTTPS doesn’t seem to be attempting to start based on what I am seeing in the logs.
Is there a good way to have it attempt to start?
Webhooks with https are not hitting the server
On Sun, Jul 15, 2018 at 7:35 AM, Joe Keenan <notifications@github.com> wrote:


> On Jul 15, 2018, at 7:32 AM, brandonjones24 <notifications@github.com> wrote:
>
> Ah, thanks!
> OK, rookie question, what should my internal port be set to? Currently it’s the default in my indigo server start page.

Same as the external, which is the same as configured in the plugin. Or more accurately, the internal port is what’s configured in the plugin. The external can be different, it’s what you use in the IFTTT URL.

**Comment by FlyingDiver** [comment]
> On Jul 15, 2018, at 7:40 AM, brandonjones24 <notifications@github.com> wrote:
> 
> Thanks for your patience. That mistake on my part caused the HTTP issues. HTTPS doesn’t seem to be attempting to start based on what I am seeing in the logs.
> Is there a good way to have it attempt to start?
> Webhooks with https are not hitting the server

You have a (different) port number in the https field?  It should start if there’s a non-zero number in that field. You might need to reload the plugin.

**Comment by brandonjones24** [comment]
Yep, that did fixed it. I am fully up and running now — this works really well.
Thanks for sticking with me!

On Sun, Jul 15, 2018 at 7:47 AM, Joe Keenan <notifications@github.com> wrote:


> On Jul 15, 2018, at 7:40 AM, brandonjones24 <notifications@github.com> wrote:
>
> Thanks for your patience. That mistake on my part caused the HTTP issues. HTTPS doesn’t seem to be attempting to start based on what I am seeing in the logs.
> Is there a good way to have it attempt to start?
> Webhooks with https are not hitting the server

You have a (different) port number in the https field? It should start if there’s a non-zero number in that field. You might need to reload the plugin.

**Comment by FlyingDiver** [comment]
Good.
